### ISSUE TITLE
Support cluster outputs

### ISSUE THREAD

**Issue by JohnGarbutt** [stackhpc/azimuth-caas-operator#15]
We need to get the outputs from the final debug line, and get hold of those.

**Comment by jjo93sa** [comment]
Having explored using cluster inputs, it doesn't seem we can get the IP, just the FIP UUID.

**Comment by jjo93sa** [comment]
Looks like this is fixed, I can see all the outputs we would expect in a Compute appliance

**Comment by JohnGarbutt** [comment]
Yes, that has now been fixed.
