### ISSUE TITLE
Support complex values in extra vars

### ISSUE THREAD

**Issue by JohnGarbutt** [stackhpc/azimuth-caas-operator#33]
Currently all values are strings.

Apparently we can use schema.Dict from the kube-custom-resource package rather than typing.Dict and it would just work.

At the same time, we should also do this to properly support the choices params in the ui-meta parsing. Currently we json encode that, then decode it in azimuth, to work around the issue.

**Comment by mkjpryor** [comment]
@JohnGarbutt

Do you want me to take a look at this? I want this fixed before merging the Azimuth patch as the hacks that you need because of it in Azimuth are rubbish.

**Comment by JohnGarbutt** [comment]
https://github.com/stackhpc/azimuth-capi-operator/blob/edda0d2da497da41ebb9df3e8d62cacac36194a4/azimuth_capi/models/v1alpha1/app_template.py#L83

**Comment by JohnGarbutt** [comment]
So the default in cluster parameter seems tricky somehow:
```
-    default: typing.Optional[str]  # TODO(johngarbutt): k8s said no if this was any!
+    default: typing.Optional[schema.Any]
```
