### ISSUE TITLE
Manually deleting failed appliances doesn't (always) work

### ISSUE THREAD

**Issue by jjo93sa** [stackhpc/azimuth-caas-operator#39]
Sometimes the following steps permits removal of failed appliances:

```
kubectl edit cluster.caas.azimuth.stackhpc.com -n <namespace> <appliance>
```
And deleting the finaliser content:
```
  finalizers:
  - kopf.zalando.org/KopfFinalizerMarker
```

But in many cases, this does not remove the appliance. Indeed, the finaliser content reappears almost immediately.

**Comment by JohnGarbutt** [comment]
Are you sure you deleted the cluster first?

**Comment by jjo93sa** [comment]
I think we can close this one. I thought I'd deleted the clusters, but could be wrong. We'll re-open if it re-occurs.
