### ISSUE TITLE
Feature request: Please handle "forever" appliances

### ISSUE THREAD

**Issue by jjo93sa** [stackhpc/azimuth-caas-operator#42]
We'd like to have a "forever" option for appliance lifetime. In this case, no scheduled deletion (i.e. no cronjob) should be created. Or, perhaps even better, a cronjob should be created but for some far off time, say the last day of 2037 to avoid the Y2K38 bug

**Comment by JohnGarbutt** [comment]
I have just merged support for this, please test it out, and report back if this works now.

**Comment by jjo93sa** [comment]
This seems to work. I created a "forever" appliance and no cronjob was created, as expected
